### PR TITLE
Bugfix 35

### PR DESCRIPTION
**Pull request by lhendey**

### CODE REVIEW

**Comment by lhendey** [comment]
@rpitingolo - so i was able to run the program Equity_Compile_ACS_for_profile.sas without a problem but Equity_ACS _Profile_transpose.sas got hung up on the PG file. The issue is that the id statement in the transpose is somehow not reading the full text of the format for councildist? I was able to temporarily fix by removing the format and running the tranpose without the format. Can you trouble shoot? Also -can you take a look at the unemployement issue mentioned in the above comment for the regional files before I rerun?

**Comment by rpitingolo** [comment]
@lhendey OK. I'll take a look at this.

**Comment by ptatian** [comment]
@lhendey @rpitingolo Can this pull request be merged and corresponding issue #35 be closed?

**Comment by lhendey** [comment]
@ptatian - i can transfer comments to a new issue and merge this one. cc @rpitingolo

**Comment by ptatian** [comment]
Thanks!

**Pull request merged**
