### PR TITLE
Adapts Housing Security IPUMS programs for Racial Equity Project

### PR DESCRIPTION
**Pull request by mwoluchem**
Copies HsngSec programs and rewrites them for this Equity task.

### CODE REVIEW

**Comment by lhendey** [comment]
@mwoluchem - have you done the low-cost housing we talked about?

**Comment by mwoluchem** [comment]
@lhendey In it right now, about to come out this afternoon!

**Comment by mwoluchem** [comment]
@lhendey It's in develop #5 if you'd like to follow there!

**Comment by mwoluchem** [comment]
@lhendey I tried to initiate the pull request but I'm not sure that it worked - did you get the correct notification?

Additionally, a quick question on the low-cost housing issue. There are a few households with more than 8 members, and there's no limit for that in the HUD documentation. I coded them as "Household is Larger than 8 people" for "aff_unit" (The variable that shows the affordability level). Is that the correct treatment of that group? You can see in tables 27-32.

**Comment by lhendey** [comment]
@mwoluchem - i revised the program to get the output I wanted (see that there is an entirely new program that ends in _rev) . can you do some spot checking on the final file compared with the proc tabulate output (in the SAS output)? I'll merge the pull request after you do that.

**Comment by lhendey** [comment]
@mwoluchem - added a step to calculate the gaps. Please sync and fill in.

**Comment by mwoluchem** [comment]
@lhendey Added the gap variables - would you mind reviewing? Prints alright, should be ok to go.

**Comment by lhendey** [comment]
@mwoluchem - I don't see a commit on this branch from you. Did you sync?

**Comment by lhendey** [comment]
@mwoluchem  - i looks like you committed the gap variables to branch #5 vs. #1. Can you revert and recommit to #1?

**Comment by mwoluchem** [comment]
@lhendey Order should be remedied. If it looks ok, I can go ahead and start on the bullets.

**Pull request merged**
