### PR TITLE
Update Equity_Regional_Profile.sas

### PR DESCRIPTION
**Pull request by lhendey**
Run for 2016-10 and add Baltimore and Richmond regions

### CODE REVIEW

**Comment by lhendey** [comment]
@rpitingolo could you do a quick review on this?

**Comment by rpitingolo** [comment]
@lhendey I'll give it a look.

**Comment by rpitingolo** [comment]
@lhendey OK to merge. One thing I wonder is if we should have a format in the General library for all the countries in the DMV (rather than just the region)? Or drop the unformatted counties in the finalize_data_set step? Typically we don't save permanent datasets that have some values unformatted.

**Comment by lhendey** [comment]
@rpitingolo fair point on formatting. i didn't want to drop because i feel like having these counties might be useful at some point - like if we had to do a DC msa. in theory we should probably just have a separate name column.

**Pull request merged**
