### PR TITLE
Calculate average loan amount for small businesses and transform geography

### PR DESCRIPTION
**Pull request by maggiesu0725**
the order of programs:

LED_pull : for small business employee counts
Equity_CRA_Pull : for calculating small business loan (less than 1 million )3 year averages
Equity_CRAlending_transformgeo  : convert tract to cluster and ward

### CODE REVIEW

**Comment by maggiesu0725** [comment]
@rpitingolo  ready for review, cc @ptatian @lhendey

**Comment by rpitingolo** [comment]
@maggiesu0725 Equity_CRAlending_transformgeo is calling for a dataset "CRAbyTract" that doesn't seem to exist. Can you check?

**Comment by maggiesu0725** [comment]
I can see it on L in the raw folder @rpitingolo

**Comment by maggiesu0725** [comment]
It's going to be created after you run the second program I think. @rpitingolo

**Comment by rpitingolo** [comment]
@maggiesu0725 OK, let me try running it again.

**Comment by rpitingolo** [comment]
@maggiesu0725 the stata program is exporting an XLSX file. That needs to be converted into a SAS dataset for it work in the Equity_CRAlending_transformgeo.sas program. I went ahead and did it in Stat transfer and saved the new file in the raw folder.

However, now %Transform_geo_data doesn't have the right parameters set. The dat_count_vars= doesn't look correct. Can you take another pass and test the program and then let me know when it's ready for another review?

**Comment by maggiesu0725** [comment]
@rpitingolo variable names are fixed. But when I use stattransfer to convert the excel file to sas, tract ID seems lost, could you take a look at both in the raw folder?

**Pull request merged**
