### PR TITLE
update ACS vars and add broadband access for equity indicator

### PR DESCRIPTION
**Pull request by maggiesu0725**

### CODE REVIEW

**Comment by maggiesu0725** [comment]
I think these are the only two programs that need to be updated. Ready for review- @lhendey

**Comment by lhendey** [comment]
@maggiesu0725 - double checking with Alice that she still wants the post secondary education indicator separate. also you didn't actually include broadband in the output. I added the modification statement and a macro variable for the year label in https://github.com/NeighborhoodInfoDC/Equity/pull/72/commits/a6b35bd5630b050afc8e19fedd4f114b3f88d05f

**Comment by lhendey** [comment]
@maggiesu0725 - can you add the post secondary education indicator code from the separate file to the Equity_compile_feature_data.sas program so it can be merged in with the other variables?

**Comment by maggiesu0725** [comment]
I can't open SAS today even after restarting my computer, will get to this as soon as I fix sas. @lhendey

**Comment by maggiesu0725** [comment]
ready for review before I generate the tables. @lhendey

**Comment by lhendey** [comment]
@maggiesu0725 - i'm getting errors when batch submitting. 

NOTE: Line generated by the macro variable "CALC_VARS_LABELS".
237         "education attainment"
            ______________________
            22
            200

ERROR 22-322: Syntax error, expecting one of the following: a name, ;.  
16 The SAS System                                                                                 17:34 Friday, May 10, 2019

**Comment by maggiesu0725** [comment]
SOrry about that, should be fixed. I just removed that line of code. @lhendey

**Comment by lhendey** [comment]
@maggiesu0725 okay to merge. Next time please double check output and logs before tagging me for reviews.

**Pull request merged**
